### ISSUE TITLE
Requesting  for yt revanced extended magisk module 

### ISSUE THREAD

**Issue by Chndnngr** [revanced-apks/build-apps#100]
Hey, will there be a yt revanced extended magisk module, the zip folder one, the updated one..  I request for it. Please give it a look, i can't do it because i am a tech noob... so please give updated yt rex magisk module, thanks.

**Comment by rabilrbl** [comment]
We have recently updated build script and there was an issue with magisk update. Hence I thought to close magisk for now. Let me see what I can do to resolve it and enable back whenever possible. 

Closing for now!
