### ISSUE TITLE
Problem opening videos

### ISSUE THREAD

**Issue by selenium2106** [revanced-apks/build-apps#109]
I don't know if what I'm going to describe has happened to anyone before: I had to update because the video not available message started to appear, telling me in the video window that it is not available for this app, to update to the latest version of YouTube to be able to see the content. In response to that I came to this repository to update my version of YouTube revanced. See if that solved my problem, but it didn't work, the same message appeared again. If anyone knows and has solved this, please tell me how to solve it, thanks for your attention. [Screenshot_20240327-223502_YouTube](https://github.com/revanced-apks/build-apps/assets/131538899/95643c59-dfda-416c-be50-39a5e206a006)

**Comment by crotoc** [comment]
Same here! Start today.

**Comment by Deimedra** [comment]
Hi, having the same problem but found a solution. You need to desinstall all youtube revanced and microg too. Next, download the official youtube apk version 19.09.37 and revanced manager. Open revanced manager and in patcher, go storage to find the youtube apk previously downloaded. The manager gonna patch it and notify you to install it. This version worked for me 😁😁

Apk youtube : https://apkcombo.com/fr/youtube/com.google.android.youtube/download/phone-19.09.37-apk

**Comment by SilverSilence** [comment]
I have the same issue.

Doing what Deimedra said didn't work for me because the patcher can't install YouTube because it can't install the pre-installed version (when I try to uninstall it, it doesn't work eihter).

**Comment by crotoc** [comment]
> Hi, having the same problem but found a solution. You need to desinstall all youtube revanced and microg too. Next, download the official youtube apk version 19.09.37 and revanced manager. Open revanced manager and in patcher, go storage to find the youtube apk previously downloaded. The manager gonna patch it and notify you to install it. This version worked for me 😁😁
> 
> Apk youtube : https://apkcombo.com/fr/youtube/com.google.android.youtube/download/phone-19.09.37-apk

Thanks! I did the same thing and works well. 
1. Download and install revanced manager: https://github.com/revanced/revanced-manager
2. Download youtube of correct version: https://www.apkmirror.com/apk/google-inc/youtube/youtube-19-09-37-release/youtube-19-09-37-android-apk-download/download/?key=028c344d6907275cc4e018d976408c509ce9f628&forcebaseapk=true
3. Use revanced manager to patch the youtube apk. Install the patched youtube.
4. Install recanced gmscore: https://github.com/ReVanced/GmsCore/releases
6.If you have huawei phone, install a stock youtube and login your account in gmscore. uninstall the stocked youtube and keep the revanced youtube: https://www.reddit.com/r/revancedapp/s/RId5IOKegr
7. Enjoy

**Comment by selenium2106** [comment]
> > Hi, having the same problem but found a solution. You need to desinstall all youtube revanced and microg too. Next, download the official youtube apk version 19.09.37 and revanced manager. Open revanced manager and in patcher, go storage to find the youtube apk previously downloaded. The manager gonna patch it and notify you to install it. This version worked for me 😁😁
> > Apk youtube : https://apkcombo.com/fr/youtube/com.google.android.youtube/download/phone-19.09.37-apk
> 
> Thanks! I did the same thing and works well.
> 
> 1. Download and install revanced manager: https://github.com/revanced/revanced-manager
> 2. Download youtube of correct version: https://www.apkmirror.com/apk/google-inc/youtube/youtube-19-09-37-release/youtube-19-09-37-android-apk-download/download/?key=028c344d6907275cc4e018d976408c509ce9f628&forcebaseapk=true
> 3. Use revanced manager to patch the youtube apk. Install the patched youtube.
> 4. Install recanced gmscore: https://github.com/ReVanced/GmsCore/releases
> 5. If you have huawei phone, install a stock youtube and login your account in gmscore. uninstall the stocked youtube and keep the revanced youtube: https://www.reddit.com/r/revancedapp/s/RId5IOKegr
> 6. Enjoy

Thank you very much, it's back to workingJust follow the steps to the letter and it will most likely work for you too.

**Comment by rabilrbl** [comment]
I hope this issue has been solved on the New ReVanced YouTube. We recommend you go with clean install for both YouTube and new microg

ReX users will need to wait for some time, as a temporary fix follow https://www.reddit.com/r/revancedextended/s/6dnYCURIH9

Feel free re open this issue
