### ISSUE TITLE
Video play/pause icon sometimes goes missing. 

### ISSUE THREAD

**Issue by anurag565** [revanced-apks/build-apps#110]
Bug in youtube rex version 19.11.39
Android 14 One UI 6.0
Device M13 5G
![Screenshot_20240328_161552_YouTube](https://github.com/revanced-apks/build-apps/assets/143786347/2827a15c-06cc-4140-8c9a-4626107618e4)
The overlay button for play/pause on videos goes missing and it should behave like screenshot shown above. But sometimes, no matter how much you tap on screen, it just wont come. But once you close the video and reopen it, it works normally.

**Comment by rabilrbl** [comment]
Hey @anurag565 

Our repo is responsible only for building ReX YouTube, please create this issue at original repo from the author at https://github.com/anddea/revanced-patches

Thank you

**Comment by anurag565** [comment]
> Hey @anurag565
> 
> Our repo is responsible only for building ReX YouTube, please create this issue at original repo from the author at https://github.com/anddea/revanced-patches
> 
> Thank you

What tool you used to make ReX? RVX manager, RVX builder, Revancify or CLI

**Comment by rabilrbl** [comment]
> > Hey @anurag565
> > 
> > Our repo is responsible only for building ReX YouTube, please create this issue at original repo from the author at https://github.com/anddea/revanced-patches
> > 
> > Thank you
> 
> What tool you used to make ReX? RVX manager, RVX builder, Revancify or CLI

ReVanced CLI
