### ISSUE TITLE
Not available on this version

### ISSUE THREAD

**Issue by chauhaniic** [revanced-apks/build-apps#111]
Showing, this video is not available on this version of YouTube. Use latest version of YouTube app to watch this video. It occurs on all video

**Comment by XanaGremory** [comment]
Same problem, i'm change the microg but i have new problem, the video have unlimited buffer

**Comment by sarowarhosen03** [comment]
![Screenshot_20240330-170851](https://github.com/revanced-apks/build-apps/assets/98280301/21ea371b-7287-44b8-9f1e-54acc6734f9b)
same issu

**Comment by KasaiKonoru** [comment]
only update your revanced yt app @sarowarhosen03

**Comment by sarowarhosen03** [comment]
> only update your revanced yt app @sarowarhosen03

 solved by update YouTube revanced app thanks

**Comment by rabilrbl** [comment]
It is fixed in latest release

Feel free to re-open if issue persist
