### ISSUE TITLE
Huawei can't log in

### ISSUE THREAD

**Issue by MartinV231** [revanced-apks/build-apps#112]
Whenever you try to log in the new microG services, it saya sorry there was a problem with communicating the servers.. Please fix this :')

**Comment by OmarMahmoud-Linux** [comment]
![Screenshot_20240330_152159](https://github.com/revanced-apks/build-apps/assets/77502459/0ce63971-7960-40cb-a793-7a818331377e)
I managed to get it working using these settings in the new microG services.

Make sure not to login in microG (login from opening YouTube for the first time after installation) to avoid playback error after 30 seconds from playing any video

**Comment by tmxdxd** [comment]
thanks bro

**Comment by car45167** [comment]
It works but the video playing blocks after 1-2 min and i have to close the app to make it work again

**Comment by MartinV231** [comment]
The login method worked! But I can't watch videos after 40 sec.. :/

**Comment by rabilrbl** [comment]
We only recommend using GmsCore available at https://github.com/ReVanced/GmsCore/releases/latest


For buffering issues in new microg check https://t.me/revanced_apks_chat/3504

If issue persist, feel free to re open
