### ISSUE TITLE
Its always says 

### ISSUE THREAD

**Issue by stevenwhat68** [revanced-apks/build-apps#113]
the following content is not available on this app version youtube

**Comment by SEAL300** [comment]
Me too

**Comment by nvn152** [comment]
Banned I guess

**Comment by Zoka93** [comment]
Go to Settings - ReVanced Extended -> Miscellaneous -> Enable "Spoof player parameter". If it's already enabled, disable it.

Restart YouTube and try again.

This Works With Me .

**Comment by nvn152** [comment]
> Go to Settings - ReVanced Extended -> Miscellaneous -> Enable "Spoof player parameter". If it's already enabled, disable it.
> 
> Restart YouTube and try again.
> 
> This Works With Me .

Worked for me too.

**Comment by mustis85** [comment]
> Go to Settings - ReVanced Extended -> Miscellaneous -> Enable "Spoof player parameter". If it's already enabled, disable it.
> 
> Restart YouTube and try again.
> 
> This Works With Me .

Its work for me... Thanks!!!

**Comment by labeedee** [comment]
> Go to Settings - ReVanced Extended -> Miscellaneous -> Enable "Spoof player parameter". If it's already enabled, disable it.
> 
> Restart YouTube and try again.
> 
> This Works With Me .

i had to toggle it on, restart, back off, then restart, but it ended up working for me as well. thanks!

**Comment by stevenwhat68** [comment]
Thankssss it also works for mine.

**Comment by aravindk64** [comment]
> Go to Settings - ReVanced Extended -> Miscellaneous -> Enable "Spoof player parameter". If it's already enabled, disable it.
> 
> Restart YouTube and try again.
> 
> This Works With Me .

Thanks it's working.....

**Comment by labeedee** [comment]
> > Go to Settings - ReVanced Extended -> Miscellaneous -> Enable "Spoof player parameter". If it's already enabled, disable it.
> > Restart YouTube and try again.
> > This Works With Me.
> 
> Thanks, it's working..... But after a few minutes, the video was stopped and its buffer

same experience. it's either nonstop buffering, or every other minute the video stutters and goes back a few seconds before resuming

**Comment by rabilrbl** [comment]
It should be fixed in latest release

Closing
Feel free to re open if issue persist

**Comment by Benlee1129** [comment]
> > > Go to Settings - ReVanced Extended -> Miscellaneous -> Enable "Spoof player parameter". If it's already enabled, disable it.
> > > Restart YouTube and try again.
> > > This Works With Me.
> > 
> > 
> > Thanks, it's working..... But after a few minutes, the video was stopped and its buffer
> 
> same experience. it's either nonstop buffering, or every other minute the video stutters and goes back a few seconds before resuming

I have the same experience.
