### ISSUE TITLE
YouTube anddea 

### ISSUE THREAD

**Issue by xaloundros** [revanced-apks/build-apps#115]
Why with YouTube anddea everytime when I try to open it ask me to install microg but I already have the latest version any suggestions please?

**Comment by Zoka93** [comment]
Try V5.3 https://github.com/WSTxda/MicroG-RE

**Comment by xaloundros** [comment]
Thank you.. I try it but I can't play any videos unfortunately

**Comment by rabilrbl** [comment]
New Anddea youtube comes with GMSCore support.
Download new microg at https://github.com/ReVanced/GmsCore/releases/latest
and give all permissions for new microg

Closing as fixed
Feel free to re open
