### ISSUE TITLE
[Project Query] GitHub workflow's release description

### ISSUE THREAD

**Issue by Rafee-M** [revanced-apks/build-apps#117]
Hi, I wanted to ask which part of the code handles the release description. I found the code handling the changelog inside [matrix-build.yml](https://github.com/revanced-apks/build-apps/blob/main/.github/workflows/matrix-build.yml) line 34. I was unable to find the other stuff in the release description (announcement, etc) though and would really appreciate it if you could help me.

Thanks.

**Comment by rabilrbl** [comment]
We have custom python script at telegram-script folder in source

At line 185 in matrix-build.yml it is executed, it generates release notes and sents it to telegram channel

![image](https://github.com/revanced-apks/build-apps/assets/63334479/a9d82b05-cf25-4c5e-8af3-8bc733bcf4cf)

**Comment by Rafee-M** [comment]
Ah okay thanks a lot for the explanation! I assumed the announcement section was added separately, but it's actually part of the anddea release notes. 

Thanks!
