### ISSUE TITLE
Playback feeds option

### ISSUE THREAD

**Issue by aravindk64** [revanced-apks/build-apps#118]
Can anyone help where can I find playback in the feeds option there is no general option herein new version. Example in this screenshot.
![Screenshot_20240401-140921__01](https://github.com/revanced-apks/build-apps/assets/55388457/ec27d518-4c03-4c7a-a19f-a2d22008c68c)

**Comment by J66788777** [comment]
Yes, the General option is missing in youtube-anddea-v19.11.38-all.apk but it is there in youtube-revanced-v19.09.37-all.apk
