### ISSUE TITLE
Latest microG GMSCORE not supported

### ISSUE THREAD

**Issue by sr-shishir** [revanced-apks/build-apps#119]
The latest microG link which you have provided it's not working on YouTube anddea version 19.12.41. When I open anddea youtube it's redirecting to inotia00 vanced microG which is not working anymore. So fix this microG issue with this version then release the apk file.

**Comment by rabilrbl** [comment]
Youtube Anddea 19.12 is not supprted.
Try Youtube Anddea 19.11 from latest release.
