### ISSUE TITLE
Ads in facebook revanced module

### ISSUE THREAD

**Issue by Chndnngr** [revanced-apks/build-apps#122]
Facebook revanced app is showing too many ads on the home screen, i think the patches aren't working as intended, please see to it and fix it, other than that  the app works great

**Comment by Scarlaid** [comment]
What about Facebook LCR on telegram

**Comment by Chndnngr** [comment]
Can you provide me the please for the telegram channel? Bcus i haven't found it on Google

**Comment by rabilrbl** [comment]
We only build and publish APKs

Rest is part of https://github.com/revanced/revanced-patches

Please create an issue there
