### ISSUE TITLE
revanced config.toml

### ISSUE THREAD

**Issue by alsyundawy** [revanced-apks/build-apps#124]
[Music-anddea]
enabled = true
app-name = "Music"
version = "latest"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[YouTube-anddea]
enabled = true
app-name = "YouTube"
version = "auto"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-Extended]
enabled = true
app-name = "Music"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "Music ReVanced Extended"
build-mode = "apk"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"                                            # both arm64-v8a and arm-v7a

[YouTube-Extended]
enabled = true
build-mode = "both"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "Youtube ReVanced Advanced"
build-mode = "apk"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

**Comment by rabilrbl** [comment]
WTF is this?

**Comment by alsyundawy** [comment]
this wtf conf.toml
