### ISSUE TITLE
Please update the base apk for Instagram-Revanced

### ISSUE THREAD

**Issue by chitranshnehra** [revanced-apks/build-apps#125]
I know the same request was opened by someone else on March 8th, and you've said it right: this fork only builds apk; report it to the Revanced team, but I've confirmed that the Revanced patch for Instagram is valid for any version.

So what is the problem? Here it is: in the config.toml file inside the build-apps, the source file for Instagram is achieve of j-hc, whereas other apps are using Uptodown's latest apk.

If you change the source, then the problem that some might be facing, i.e., updating the app popup, will be resolved. Please take care to do so.

disclamer: I might be unaware of any issue that you are facing in updating the source. For that, I'm sorry. Thank you.

![image](https://github.com/revanced-apks/build-apps/assets/95127569/7d02ae67-be2f-4d84-9824-0f42b38a1d85)

**Comment by chitranshnehra** [comment]
It is working; I have verified it; I just need to remove both old Instagram lines (image attached above) and insert this:

[Instagram]
enabled = true
version = "auto"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "both"

**Comment by rabilrbl** [comment]
Ok, let me check with beta builds

**Comment by rabilrbl** [comment]
Done
