### ISSUE TITLE
Youtube buffering 

### ISSUE THREAD

**Issue by syednaumanjamil** [revanced-apks/build-apps#127]
After clicking on any video on YouTube revanced its keep on buffering for like ages
Kimdly resolve this issue

**Comment by KazuyaRito** [comment]
I have the same problem, I thought my phone had a problem, I uninstalled and reinstalled and still have this problem

**Comment by jbdu47** [comment]
Samedi issue

**Comment by itzzyaseen** [comment]
Yes I am also facing buffering issue, please resolve

**Comment by Jzznllvnc** [comment]
Same issue, video took ages to start or not start at all. Please fix

**Comment by Vivu5772** [comment]
Same issue

**Comment by J66788777** [comment]
Works fine here on v2024.04.21-1803 youtube-anddea-v19.11.38-all.apk

For a Month now with no issue

**Comment by LeVraiRoiDHyrule** [comment]
Same issue here
