### ISSUE TITLE
Option to filter out videos that have a TikTok shop link

### ISSUE THREAD

**Issue by farhan1666** [revanced-apks/build-apps#130]
**Is your feature request related to a problem? Please describe.**
Even though TikTok vanced removes official ads, it's almost pointless since every 5th video is someone trying to sell you something on TikTok shop. These are essentially ads themselves as they rarely serve the purpose to entertain and are usually very low effort. At least some of the official ads are entertaining lol.

**Describe the solution you'd like**
Add an option to never see videos that have a TikTok shop link. Whilst this may get rid of some videos where the sole purpose isn't to sell you something, it would be a massive improvement from the current state of the app.

**Describe alternatives you've considered**
Far more complicated, but a crowdsourced "This is an ad" button for videos of this nature. If x% of revanced users declare a video an ad, it will not be shown based on the users preferences.

**Additional context**
Worth noting on my phone, I always get a sliding puzzle captcha when a TikTok shop video comes up, without fail. Not sure if this is relevant but thought I should mention it.

**Comment by rabilrbl** [comment]
We only build apks. 
Patches are from https://github.com/revanced/revanced-apks Report there
