### ISSUE TITLE
Potential virus/malware in the facebook apk in releases section

### ISSUE THREAD

**Issue by PrabhakarManara** [revanced-apks/build-apps#131]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**

**Describe the bug of the rvmm builder or the modules**

The arm64 facebook apk in https://github.com/revanced-apks/build-apps/releases/tag/143 is flagged as virus in virustotal.com website.

The file in question is  https://github.com/revanced-apks/build-apps/releases/download/143/facebook-arm64-revanced-v421.0.0.33.47-arm64-v8a.apk .

[virustotal link](https://www.virustotal.com/gui/file/b3fa898717b1b7c0bb90242d343519e93e832ddf0657a4f0b2730f8391758a5a)

**Comment by rabilrbl** [comment]
It's a false positive
