### ISSUE TITLE
Videos only load the first seconds

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [revanced-apks/build-apps#140]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

Hi,

I've updated to the latest version of RVX, and the videos only load the first few seconds. Then it buffers indefinitely. I have no problem with my network.

I also tried with normal built revanced and I'm having the same issue.

What could be the cause of this problem? What should I try?

Thanks In advance for any answer, have a nice day.

**Comment by J66788777** [comment]
Interesting... Did you install this yet? https://github.com/ReVanced/GmsCore/releases/tag/v0.3.1.4.240913

**Comment by SSB-ARFCN** [comment]
Me too 
![Screenshot_2024-07-11-12-02-45-878_app rex android youtube](https://github.com/revanced-apks/build-apps/assets/107019852/25bc269d-2699-48d1-997a-81342844b958)
![Screenshot_2024-07-11-12-02-55-162_com miui securitycenter](https://github.com/revanced-apks/build-apps/assets/107019852/c0f83c03-7411-460e-ba28-5305683c3c11)

Only play 2 sec than into loading

**Comment by rabilrbl** [comment]
Please post an issue in respective patches repository. not here
