### ISSUE TITLE
Sat,june 15 RVX YT don't work properly

### ISSUE THREAD

**Issue by Samoedraaa** [revanced-apks/build-apps#141]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

RVX YT,Same issues the video didn't play at all only for video above 4minute for video below 4minute works fine just a bit of jitter in the first part of the video
-RVX Music works fine

**Comment by J66788777** [comment]
Works fine here. Is everything up to date? RVX, MicroG, etc

If you still having problems try Spoof client in Settings > Miscellaneous

**Comment by Samoedraaa** [comment]
> Works fine here. Is everything up to date? RVX, MicroG, etc
> 
> If you still having problems try Spoof client in Settings > Miscellaneous

Yeah I have a problem for that for some reason spoof client won't work on my device,when I press spoof client on microg the checkmark don't show up but the spoof client on RVX did give me check mark

**Comment by Samoedraaa** [comment]
> > Works fine here. Is everything up to date? RVX, MicroG, etc
> > If you still having problems try Spoof client in Settings > Miscellaneous
> 
> Yeah I have a problem for that for some reason spoof client won't work on my device,when I press spoof client on microg the checkmark don't show up but the spoof client on RVX did give me check mark

Nvm just reinstalled everything it works now hope it doesn't happened again
