### ISSUE TITLE
Why Only Beta version for YouTube App ?

### ISSUE THREAD

**Issue by ankur-raikwar** [revanced-apks/build-apps#18]
If possible provide **non-beta version of YouTube App**

**Comment by rabilrbl** [comment]
Hey @ankur-raikwar ,
YouTube has unique version numbers for both stable and beta releases. As per our implementation we select the largest version, sometimes it can be the latest stable or most of the time it will be a beta version.

Currently I don't have time to refactor the code. I'm open to PRs.

Thanks
