### ISSUE TITLE
Fixed video playback speed

### ISSUE THREAD

**Issue by KapibaraSan4** [revanced-apks/build-apps#19]
With the current specs, if you change the speed while playing a video and then close the video, the playback speed is set to x1.

I'd be happy if you could specify the playback speed before stopping, like in old Vanced!
DeepLで翻訳しました https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by rabilrbl** [comment]
Please report this issue at [revanced/revanced-patches](https://github.com/revanced/revanced-patches/issues)
