### ISSUE TITLE
Instagram revanced

### ISSUE THREAD

**Issue by Ravu3467** [revanced-apks/build-apps#38]
Hello Sir, Just had a small query if you don't mind, What's there in Instagram revanced, whuch is not there in original Instagram

**Comment by james28909** [comment]
> Hello Sir, Just had a small query if you don't mind, What's there in Instagram revanced, whuch is not there in original Instagram

Maybe it doesn't have ads now. Check to see if you get as in the app.

**Comment by rabilrbl** [comment]
Refer: https://revanced.app/patches?pkg=com.instagram.android
