### ISSUE TITLE
Cannot open youtube revanced extended 

### ISSUE THREAD

**Issue by user1680** [revanced-apks/build-apps#47]
Device M13 5g
Magisk module of youtube revanced extended is asking for MicroG, but it shouldn't because my device is rooted. It didn't in previous revanced youtube extended magisk module versions.
![Screenshot_20230713_220203_ReVanced Extended](https://github.com/revanced-apks/build-apps/assets/53784071/b5f5b105-190e-44bd-b27f-2cf6769175f7)

**Comment by therealguy90** [comment]
Same issue here.

**Comment by rabilrbl** [comment]
Just install microg, as the warning says
[Download here](https://github.com/TeamVanced/VancedMicroG/releases/download/v0.2.24.220220-220220001/microg.apk)
