### ISSUE TITLE
Why is there no download link for "Sync For Reddit APK" in "releases"

### ISSUE THREAD

**Issue by minou2020** [revanced-apks/build-apps#61]
There are download links for almost all ReVanced-patched apks except Sync For Reddit
Could you please add links for the patched Sync ?

**Comment by rabilrbl** [comment]
Ok, please define the use case of the app and send package id example: `com.example.app`
I'll consider.

**Comment by minou2020** [comment]
com.laurencedawson.reddit_sync.dev

Apk is there: https://www.apkmirror.com/apk/red-apps-ltd/sync-for-reddit/sync-for-reddit-v23-05-03-1718-release/ 
Make sure you upload v 23-05-03, as the newest doesnt' work

**Comment by rabilrbl** [comment]
May I know, what the app is used for?

**Comment by minou2020** [comment]
> May I know, what the app is used for?

It was a 3rd party Reddit App with Material You 3 design
It stopped working after Reddit API Changes, but ReVanced Team released patches to make it work again.µ
However, I can't patch myself because ReVanced Manager doesn't support arm-v7A devices
