### ISSUE TITLE
Fails to build in openSUSE, what are the dependencies?

### ISSUE THREAD

**Issue by DavidOliM** [revanced-apks/build-apps#67]
**Describe the bug**
Building locally fails

**To Reproduce**
git clone, run ./build

**Expected behavior**
Builds succesfully

**Screenshots**

![Screenshot_20230826_224951](https://github.com/revanced-apks/build-apps/assets/10873838/4c0ff7d4-3931-4f77-8b40-8c8d8eecdacd)

**Smartphone (please complete the following information):**

**Additional context**
What are the dependencies? All apks fail to build in openSUSE.

**Comment by rabilrbl** [comment]
There was a bug recently, it is resolved.
If the issue is not relevant now, please close.
