### ISSUE TITLE
Not able to build with latest patch v2.189.0

### ISSUE THREAD

**Issue by marquuard** [revanced-apks/build-apps#68]
**Describe the bug**

Build modules/APKs part of Build Modules workflow is not able to build individual APKs since latest patch# v2.189.0 introduced.
Seemingly none of the APKs can be built by workflow.

**To Reproduce**
1. Go to 'Actions'
2. Start 'run' workflow

**Expected behavior**
Ability for the script to build supported APKs with patch v2.189.0

**Screenshots**
![image](https://github.com/revanced-apks/build-apps/assets/15956164/58782b15-0bcd-48a0-8ba9-a2e6ab82402d)

**Comment by marquuard** [comment]
Seemingly the type of the error has changed. Applies to almost every to-be patched APKs. Screenshot from Builder workflow (YT Revanced as an example):

<img width="619" alt="image" src="https://github.com/revanced-apks/build-apps/assets/15956164/3d985cc5-9bc0-42d9-abeb-4360575854f8">

**Comment by rabilrbl** [comment]
There has been a new upstream merge, could you please check if the error persist.

**Comment by marquuard** [comment]
That solved the problem. Build completed. Thank you.
