### ISSUE TITLE
Build error regarding a password parameter.

### ISSUE THREAD

**Issue by DoormatIka** [revanced-apks/build-apps#71]
**Describe the bug**
While running the workflow as instructed by the README.md, I found a bug insisting that there should be a password with the `-p` parameter.

**To Reproduce**
1. Fork this repository
2. Modify the config.toml and options.json according to this site: https://j-hc.github.io/rvmm-config-gen/
3. Run the GitHub workflow.

**Expected behavior**
An APK appearing in my Releases tab.

**Screenshots**
![image](https://github.com/revanced-apks/build-apps/assets/68234036/dc1e8e7d-16f5-47b0-877c-201e6772d0e9)

**Smartphone (please complete the following information):**
 - Device: Redmi 10C
 - OS: Android 11

**Additional context**
None.

**DO NOT REPORT REVANCED BUGS IN THIS REPO**
- I don't know if this counts as a Revanced bug or your bug...

**Describe the bug of the rvmm builder or the modules**

**Comment by rabilrbl** [comment]
This is an old revanced cli issue, please re-check if the issue persist by merging our latest changes from main.
