### ISSUE TITLE
Exclude "Custom Branding" from YT and YT Music (if possible) [enhancement]

### ISSUE THREAD

**Issue by minou2020** [revanced-apks/build-apps#82]
Could you please exclude "custom branding" patch for YouTube and YT Music (arm-v7A) ?

Thanks

**Comment by minou2020** [comment]
I can't patch apks myself as armv7a isn't supported by the rvx manager

**Comment by sigma2017** [comment]
You can directly install https://github.com/revanced-apks/build-apps/releases/download/177/youtube-revanced-v18.38.44-all.apk
 I don't like Extended version either even is based on a newer version.

**Comment by sigma2017** [comment]
Hello, please post youtube-revanced-v18.45.41-all.apk available for arm-v7A also if possible, ofc without custom branding.
Thanks in advance!
