### ISSUE TITLE
Youtube revanced extended history not working

### ISSUE THREAD

**Issue by Suni47** [revanced-apks/build-apps#90]
Youtube rev doesn't doesn't save watched history.

Watch a yt video then go to history, the video is not registered there.

 - Device: Redmi 12C
 - OS: Android 14

**Comment by Armagedon13** [comment]
This is not a place to put issues related to the APK, however... Go to revanced config - miscellaneous - spoof player parameter

**Comment by Armagedon13** [comment]
Rex fix it but I think it's the last update because he abandoned the project
