### ISSUE TITLE
Revanced Does not save history.

### ISSUE THREAD

**Issue by MasterFerrary** [revanced-apks/build-apps#91]
Hello, I just opened the topic, but it was about the Manager.  So I need to open it again here.
YouTube Revanced suddenly stopped showing videos I watched in the past. It only shows shorts in the past. I deleted the application and microG and reinstalled them. I restarted my phone but it didn't help. Please help me
I also cleared the history. And I turned off the save history option and turned it on again, but it didn't work. Only videos I watched on YouTube shorts appear in the past.

**Comment by darkred1145** [comment]
I think it has something to do with the Spoof playback parameter in the miscellaneous. I turned it off and it starts saving watch history again. Don't know why though.

**Comment by darkred1145** [comment]
I don't know yet.

**Comment by MasterFerrary** [comment]
No way, videos are not loading.  I cannot reach the development team to report the issue.  When will this terrible problem be solved?  Someone should report this problem to the developers!
