### ISSUE TITLE
YouTube history

### ISSUE THREAD

**Issue by Ade52286** [revanced-apks/build-apps#92]
**Describe the bug**
Good day. YouTube isn't showing/keeping video histories. The only history visible are Shorts.

**To Reproduce**
1. Go to history.

**Expected behavior**
When in history, only Shorts are recorded.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: samsung galaxy s22 

**Additional context**

**DO NOT REPORT REVANCED BUGS IN THIS REPO**

**Describe the bug of the rvmm builder or the modules**

**Comment by JobiMorkos** [comment]
Yeah same, This shit is awful like it's even deleted on YouTube official app.
