### ISSUE TITLE
Revanced History is deleted

### ISSUE THREAD

**Issue by JobiMorkos** [revanced-apks/build-apps#93]
**Describe the bug**
So before Wed (timezone) YouTube was still fine, All of the videos are still on the history but then after Wed, Everything was deleted, YouTube only left the videos that is unfunny and shorts. 

**To Reproduce**
1. Go to Library 
2. Click on History
3. Scroll down to videos
4. See all of my videos deleted

**Expected behavior**
It's probably because of MicroG syncing poorly

**Screenshots**
![IMG_20240229_180343](https://github.com/revanced-apks/build-apps/assets/138365667/26b16258-3db6-463c-9026-6f6a0e0b51a6)

![IMG_20240229_182059](https://github.com/revanced-apks/build-apps/assets/138365667/3d2f0eb2-794e-4dff-86cf-c1e5f51d1d91)

**Smartphone (please complete the following information):**
 - Device: Realme 5i
 - OS: Android 10

**Additional context**
Google YouTube history is fine and I checked all of the settings and none is modified and official app was also deleted and PC is also deleted. 

**DO NOT REPORT REVANCED BUGS IN THIS REPO**

**Describe the bug of the rvmm builder or the 
modules**

**Comment by FelipeSanchezCalzada** [comment]
Same here. Google Pixel 8 Pro
