### ISSUE TITLE
change ReX patches version to "auto"

### ISSUE THREAD

**Issue by blacktornadog7** [revanced-apks/build-apps#94]
**Describe the bug**
when patching YouTube latest version with ReX patches (which [isn't supported](https://github.com/YT-Advanced/ReX-patches/issues/129#issuecomment-1973032687)) it [crashes on startup](https://github.com/YT-Advanced/ReX-patches/issues/129)

**To Reproduce**
1. patch latest YouTube version with ReX patches
2. launch the app

**Expected behavior**
crashes on startup

**Solution**
change ReX patches version (for Youtube and YouTube Music to "auto"

**Comment by rabilrbl** [comment]
@blacktornadog7 I set it to latest because ReX dev was deliberately setting to older version even though new version was supported.

Let me see if the crash persists after new update

**Comment by rabilrbl** [comment]
Latest version is working fine
